/**
 * Safe Schema Migration
 *
 * Provides safe schema migration for content type tables.
 * Only adds new columns — never drops, renames, or alters existing ones.
 * Removed fields stay in DB but are excluded from API responses.
 */
import type { ContentTypeConfig, FieldConfig } from '../../../lib/publisher/types'
import { getProvider } from './database'
import type { SupportedDialect } from './database/provider'
import { getColumns, addColumn } from './database/dialect'
import { toSnakeCase } from './contentApi'

/**
 * System columns that are auto-generated by the schema compiler
 * and should not be considered as "removed fields" during migration.
 */
const SYSTEM_COLUMNS = [
  'id',
  'status',
  'published_at',
  'created_at',
  'updated_at',
  'deleted_at',
]

/**
 * Result of a schema migration operation.
 */
export interface SchemaMigrationResult {
  /** Columns that were added */
  added: string[]
  /** Columns that exist in DB but not in config (removed fields) */
  removed: string[]
  /** Warning messages (e.g., type changes detected) */
  warnings: string[]
}

/**
 * Compile a single field config into a SQL column definition for migration.
 *
 * This is similar to compileField() in schemaCompiler.ts but:
 * - Strips NOT NULL constraint (existing rows would violate it)
 * - Does not include UNIQUE constraint (would fail if duplicates exist)
 *
 * @param name - The field name (camelCase)
 * @param config - The field configuration
 * @param dialect - The database dialect
 * @returns SQL column definition string, or null for unsupported types
 */
function compileFieldForMigration(
  name: string,
  config: FieldConfig,
  dialect: SupportedDialect,
): string | null {
  // Validate field name to prevent SQL injection
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(name)) {
    throw new Error(`Invalid field name: "${name}". Must be alphanumeric with underscores.`)
  }

  const colName = toSnakeCase(name)
  let sqlType: string

  switch (config.type) {
    case 'string':
    case 'email':
    case 'password':
      sqlType = config.maxLength ? `VARCHAR(${config.maxLength})` : 'TEXT'
      break

    case 'text':
    case 'richtext':
      sqlType = 'TEXT'
      break

    case 'number':
      sqlType = 'INTEGER'
      break

    case 'boolean':
      sqlType = dialect === 'postgres' ? 'BOOLEAN' : 'INTEGER'
      break

    case 'date':
    case 'datetime':
      sqlType = 'TEXT' // ISO strings in both dialects
      break

    case 'uid':
      sqlType = 'TEXT'
      // Note: No UNIQUE constraint for migration (existing rows might conflict)
      break

    case 'media':
      sqlType = 'INTEGER'
      break

    case 'relation':
      if ('relationType' in config && (config.relationType === 'oneToMany' || config.relationType === 'manyToMany')) {
        sqlType = dialect === 'postgres' ? 'JSONB' : 'TEXT'
      } else {
        sqlType = 'INTEGER'
      }
      break

    case 'enum':
      sqlType = 'TEXT'
      break

    case 'json':
      sqlType = dialect === 'postgres' ? 'JSONB' : 'TEXT'
      break

    default:
      return null
  }

  // Note: We intentionally do NOT add NOT NULL for migration columns
  // because existing rows would violate the constraint.
  // We also do NOT add UNIQUE for safety.

  // Add DEFAULT if specified
  if (config.default !== undefined) {
    const defaultVal = formatDefault(config.default, dialect)
    return `${colName} ${sqlType} DEFAULT ${defaultVal}`
  }

  return `${colName} ${sqlType}`
}

/**
 * Format a default value for SQL.
 */
function formatDefault(value: unknown, dialect: SupportedDialect): string {
  if (typeof value === 'string') return `'${value.replace(/'/g, "''")}'`
  if (typeof value === 'number') return String(value)
  if (typeof value === 'boolean') {
    if (dialect === 'postgres') return value ? 'true' : 'false'
    return value ? '1' : '0'
  }
  if (value === null) return 'NULL'
  return `'${JSON.stringify(value).replace(/'/g, "''")}'`
}

/**
 * Perform safe schema migration for a content type.
 *
 * Compares the content type config fields with the actual table columns
 * and adds any new columns. Never drops or alters existing columns.
 *
 * @param config - The content type configuration
 * @returns Migration result with added columns, removed columns, and warnings
 */
export async function safeSchemaSync(config: ContentTypeConfig): Promise<SchemaMigrationResult> {
  const provider = await getProvider()
  const dialect = provider.dialect
  const tableName = `publisher_ct_${config.pluralName}`

  const result: SchemaMigrationResult = {
    added: [],
    removed: [],
    warnings: [],
  }

  try {
    // Get existing columns from the actual table
    const existingColumns = await getColumns(dialect, provider, tableName)

    // Build set of expected column names from config fields
    const configColumnNames = new Set<string>()
    for (const fieldName of Object.keys(config.fields)) {
      configColumnNames.add(toSnakeCase(fieldName))
    }

    // Find new fields that need columns added
    for (const [fieldName, fieldConfig] of Object.entries(config.fields)) {
      const colName = toSnakeCase(fieldName)

      if (!existingColumns.includes(colName)) {
        // New field — add column
        const colDef = compileFieldForMigration(fieldName, fieldConfig, dialect)
        if (colDef) {
          const sql = addColumn(dialect, tableName, colName, colDef.replace(/^\w+\s+/, ''))
          try {
            await provider.execute(sql)
            result.added.push(colName)
          } catch (err) {
            // Column might have been added by another process
            const message = err instanceof Error ? err.message : String(err)
            if (!message.includes('duplicate column') && !message.includes('already exists')) {
              result.warnings.push(`Failed to add column '${colName}': ${message}`)
            }
          }
        }
      }
    }

    // Find columns that exist in DB but not in config (removed fields)
    for (const existingCol of existingColumns) {
      // Skip system columns
      if (SYSTEM_COLUMNS.includes(existingCol)) continue

      // Check if this column corresponds to a config field
      if (!configColumnNames.has(existingCol)) {
        result.removed.push(existingCol)
      }
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    result.warnings.push(`Schema sync failed: ${message}`)
  }

  return result
}

/**
 * Get the list of field names that should be included in API responses.
 * Excludes removed fields (columns that exist in DB but not in config).
 *
 * @param config - The content type configuration
 * @param existingColumns - The actual columns in the table
 * @returns Set of camelCase field names that should be included
 */
export function getActiveFieldNames(
  config: ContentTypeConfig,
  existingColumns: string[],
): Set<string> {
  const activeFields = new Set<string>()

  // Always include system fields
  activeFields.add('id')

  if (config.options?.draftAndPublish) {
    activeFields.add('status')
    activeFields.add('publishedAt')
  }

  if (config.options?.timestamps !== false) {
    activeFields.add('createdAt')
    activeFields.add('updatedAt')
  }

  if (config.options?.softDelete) {
    activeFields.add('deletedAt')
  }

  // Include all fields from config
  for (const fieldName of Object.keys(config.fields)) {
    activeFields.add(fieldName)
  }

  return activeFields
}
